### ISSUE TITLE
Missing syntax highlighting

### ISSUE THREAD

**Issue by Kapiainen** [Kapiainen/SublimePapyrus#11]
Certain keywords (e.g. self, parent, as, auto) are still missing proper syntax highlighting.

Thanks to Scrivener07 for bringing this to my attention.

**Comment by Scrivener07** [comment]
I noticed today that the "Idle" base script is missing highlighting too. This is a base script with no members though shows up in scripts as properties and variables. Maybe some other memberless base scripts are missing too.
