### ISSUE TITLE
Syntax highlighter is broken by backslash string delimiter.

### ISSUE THREAD

**Issue by Scrivener07** [Kapiainen/SublimePapyrus#12]
Here is a sample of some papyrus code that breaks the syntax highlighter.

```
;1 = Newline
;2 = Tab
;3 = Double quote
;4 = Backslash
string Function GetDelimiter(int aiDelimiter = 1) Global
	If(aiDelimiter == 1)
		return "\n"
	ElseIf(aiDelimiter == 2)
		return "\t"
	ElseIf(aiDelimiter == 3)
		return "\""
	ElseIf(aiDelimiter == 4)
		return "\\"
		return "\\" ; this fixes the sublime syntax highlighter
	Else
		return ""
	EndIf
EndFunction
```

I use this silly function solely to prevent the highlighter from breaking. If you remove the extra return then everything under that line will use the yellow "string" highlighting.

**Comment by Kapiainen** [comment]
This is no longer an issue in the rewrite that I'm currently working on.
