### ISSUE TITLE
Won't create INI, nothing happens

### ISSUE THREAD

**Issue by perrybutler** [Kapiainen/SublimePapyrus#13]
If I press CTRL+SHIFT+P I can see the SublimePapyrus Create Default INI command, but when I choose it nothing happens. There is no INI in My Documents. I tried creating the INI there manually, but it doesn't seem recognize it. Running as admin. Tried in SublimeText 2, 3, and portable, same result. What am I doing wrong?

**Comment by Kapiainen** [comment]
Have you checked if there are any relevant errors in Sublime Text's console (View -> Show Console)?

**Comment by perrybutler** [comment]
Hello! Thanks for responding.

Running the command shows this in the console:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\SPB_Data\\Documents\\SublimePapyrus.ini'

That's not a typical My Documents path. What is SPB_Data? I'm on Windows 7 64-bit.

**Comment by Kapiainen** [comment]
Odd. The default path that is used is generated by Python's *os.path.expanduser* function and it should return a valid path.

SublimePapyrus has a setting called [*ini_path*](https://github.com/Kapiainen/SublimePapyrus/blob/master/Core/SublimePapyrus.sublime-settings#L5). That setting lets you override the default path. Try entering a path that is valid there (filename included).

**Comment by perrybutler** [comment]
Holy crud it worked! Here's how for anyone struggling...

Let's say you have Skyrim installed under C:\Skyrim. First create the SublimePapyrus.ini file, let's say under C:\SkyrimUtils\SublimePapyrus.ini.

In that file include the following:

[Skyrim]
scripts=C:\Skyrim\Data\Scripts\Source
compiler=C:\Skyrim\Papyrus Compiler\PapyrusCompiler.exe
output=C:\Skyrim\Data\Scripts
workspace=
flags=TESV_Papyrus_Flags.flg

Now open Sublime Text and choose Preferences > Package Settings > SublimePapyrus > Settings - User and added this to the empty file:

{
	"ini_path": "C:/SkyrimUtils/SublimePapyrus.ini",
}

Note the use of forward slashes here instead of the typical backslash. Save and close the file. Now hit F7 and the compiler should run.

Thanks a lot for the package! This is going to save some time. You can't even highlight multiple lines in Creation Kit's script editor and hit tab to indent - it deletes all the highlighted text. :D

**Comment by perrybutler** [comment]
An update for my previous comment. IF you're using Mod Organizer, you'll want to set the output= path to your Mod Organizer's overwrite/scripts folder, e.g:

output=C:\SkyrimUtils\ModOrganizer\overwrite\scripts

What was happening is that my script would compile to C:\Skyrim\Data\scripts, but then Mod Organizer would overwrite with an older compiled script that was in C:\SkyrimUtils\ModOrganizer\overwrite\scripts, so my compile would never take effect.
