### ISSUE TITLE
'Toggle Comment' commands no longer working

### ISSUE THREAD

**Issue by akor79** [Kapiainen/SublimePapyrus#24]
Since I updated to version 2.4.0 yesterday, I noticed that the sublime commands for toggling comments are no longer working for 'Papyrus - Skyrim' files.

> Edit -> Comment -> Toggle Comment (Ctrl+/) | Toggle Block Comment (Ctrl+Shift+/)

I'm not sure if this is this is really a issue with SublimePapyrus, but it was working with the previous version I was using (v1.x, don't remember exactly which one I had before).

**Comment by Kapiainen** [comment]
Fixed in version 2.5.0.
