### ISSUE TITLE
Another Code Completion issue

### ISSUE THREAD

**Issue by jimkaiseriv** [Kapiainen/SublimePapyrus#33]
I had another issue with Code Completion. I wasn't sure if you'd prefer me to append it to my previous report as a new comment, or start a new thread this way. But, since the new error seems to be caused in some other part of the plugin's code, I figured that creating a new thread was preferable.

As near as I can tell, the code completion stopped working while I was in the middle of creating either an if statement or a while loop. This time around, I did not save or compile the code as a precursor to the failure. Instead, it _seemed_ as if everything was working fine while editing one line, then stopped in the middle of editing the next. The console reported this error:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 236, in on_query_completions
  File ".\Plugin.py", line 507, in on_query_completions
  File ".\Plugin.py", line 604, in Completions
AttributeError: 'EmptyStateCancel' object has no attribute 'keywords'

The failure occurred while I was writing some control code that accessed properties and functions in another script of mine that is part of the same project, However, neither script extends the other, and the script I was referencing had no syntactical errors and did compile fine both before and after this point. Code completion was working while referencing properties from the same script just one or two lines before.

I should mention that I had not yet updated to version 2.6.4, but that I had previously turned linter_panel_error_messages to false as a temporary workaround for the previous bug I reported. 

EDIT: I just updated to 2.6.4, and got the same problem almost right away. Code completion worked on one line (the one where it failed last time), I moved on to writing another function, and it stopped again. The circumstances were similar: I was referencing a function in another script, same as before. The console error is also nearly identical. I've copied it below.

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 236, in on_query_completions
  File ".\Plugin.py", line 509, in on_query_completions
  File ".\Plugin.py", line 606, in Completions
AttributeError: 'EmptyStateCancel' object has no attribute 'keywords'

**Comment by Kapiainen** [comment]
This looks like it could take a while to wrap my head around because:
- the line referred to in the error message is generating completions by handling a custom exception (**ExpectedKeywordError**) raised by the linter in regards to a missing keyword (either **Auto** or **AutoReadOnly**) in a property declaration (with a default value) in a Papyrus script
- the only instance of code that raises the aforementioned exception in the linter also explicitly ensures that the exception constructor has a value to assign to an attribute called **keywords**

So it seems like the exception should not have been raised, unless you were in the process of declaring a property with a default value, and in any case the exception should definitely have a **keywords** attribute.

**Comment by Kapiainen** [comment]
This is a case of a stereotypical bug; a typo in the code. Fixed in [version 2.6.6](https://github.com/Kapiainen/SublimePapyrus/releases/tag/2.6.6). Thanks for reporting it.

**Comment by jimkaiseriv** [comment]
No problem. Thank you for creating/maintaining this plugin.

**Comment by jimkaiseriv** [comment]
I'd just like to make a small observation. It seems as if code completion does not take place as expected while typing out a return value for a function. The plugin will finish typing out "Return" if I push tab after typing the first few letters of the keyword. However, after that, it does not offer any suggestions as I type or complete anything for what follows immediately on that line (whether a variable or property, or even a basic keyword like True/False). However, if I type out the full name of a property, code completion begins again after the dot operator. So, for example, Return someformlist.GetSize() will suggest/complete ".GetSize()", but not "someformlist." This does not appear to interfere with code completion on any other line, and I've noticed no console errors. I am observing this on Version 2.6.6.

**Comment by Kapiainen** [comment]
I'll look into it when I get the chance.

**Comment by Kapiainen** [comment]
The missing completions should be fixed in version 2.6.7.

**Comment by jimkaiseriv** [comment]
Thanks again. Your work on this plugin is greatly appreciated!
