### ISSUE TITLE
Linter crash report

### ISSUE THREAD

**Issue by jimkaiseriv** [Kapiainen/SublimePapyrus#34]
Ran into another instance where the linter crashed, partially. I did not notice that there was a problem at first because the plugin continued to work as expected when dealing entirely with locally defined functions, variables, etc. However, it no longer was able to supply completions for anything in parent scripts, or any other script for that matter. I found the following error in the console:

Exception in thread Thread-14621:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 736, in run
  File ".\Plugin.py", line 465, in Linter
  File "C:\Users\Kaisers\AppData\Roaming\Sublime Text 2\Packages\SublimePapyrus - Skyrim\Linter.py", line 1703, in Process
    extends = self.GetLineage(self.header.data.parent)
  File "C:\Users\Kaisers\AppData\Roaming\Sublime Text 2\Packages\SublimePapyrus - Skyrim\Linter.py", line 1551, in GetLineage
    if not self.CacheScript(name, fullPath):
  File "C:\Users\Kaisers\AppData\Roaming\Sublime Text 2\Packages\SublimePapyrus - Skyrim\Linter.py", line 1619, in CacheScript
    if statements[0].type == self.STAT_SCRIPTHEADER:
IndexError: list index out of range

It seems to have occurred when attempting to save or build a file that had an error in it. I'm not sure of the exact circumstances, however, since I did not notice the problem for a little while. I can say, however, that I was working on changing how inheritance worked on a few scripts. Whereas previously I had something like:

ScriptName parentscript Extends quest

ScriptName childscript Extends parentscript

I was inserting a script in between the two, so I had:

ScriptName parentscript Extends quest

ScriptName intermediary Extends parentscript

ScriptName childscript Extends intermediary

The condole error occurred in the middle of making these changes.

**Comment by Kapiainen** [comment]
I was able to replicate the issue and it looks like I had subconsciously assumed certain behavior (i.e. saving often) while implementing the caching mechanism.

I think you may have created the **intermediary** script as a file, opened it in Sublime Text, typed out the script header, and modified **childscript**'s script header without saving **intermediary** in between. So **intermediary.psc** would have been a blank file and the script header that you typed out would only have existed in Sublime Text's buffer. The linter ended up trying to cache an empty script while assuming that **intermediary.psc** would be a valid script.

A new version that fixes the issue should be available later today or tomorrow.

**Comment by jimkaiseriv** [comment]
The sequence of events you described sounds likely. Glad you could find the problem, and thanks for all your work!

**Comment by Kapiainen** [comment]
[Version 2.6.8](https://github.com/Kapiainen/SublimePapyrus/releases/tag/2.6.8) should fix the issue.

**Comment by jimkaiseriv** [comment]
Just installed the packages, but I got an error immediately after saving for the first time:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 190, in on_post_save
  File ".\sublime_plugin.py", line 154, in run_timed_function
  File ".\sublime_plugin.py", line 189, in <lambda>
  File ".\Plugin.py", line 174, in on_post_save
  File ".\Plugin.py", line 463, in Linter
  File "C:\Users\Kaisers\AppData\Roaming\Sublime Text 2\Packages\SublimePapyrus - Skyrim\Linter.py", line 1692, in Process
    self.Abort("No paths were given to process.")
  File "C:\Users\Kaisers\AppData\Roaming\Sublime Text 2\Packages\SublimePapyrus - Skyrim\Linter.py", line 1367, in Abort
    if self.statements and self.statementsIndex < len(self.statements):
AttributeError: 'Semantic' object has no attribute 'statements'

**Comment by Kapiainen** [comment]
Try the new version, 2.6.9. By the way, the original error message refers to not receiving any paths for import folders (i.e. folders that contain the Papyrus source files). Did your user settings for this package have the import paths properly defined when the error occurred?

**Comment by jimkaiseriv** [comment]
Looks like my paths weren't set. When I configured my compiler/import paths, etc., for this plugin, I had (foolishly) edited the default settings instead of modifying them in the user settings. I haven't had a problem with them getting wiped until this latest version, which is why I didn't realize they had been overwritten until you mentioned it. Both 2.6.8 and 2.6.9 are working with the paths properly set.

**Comment by Kapiainen** [comment]
Okay, thanks for confirming what I had suspected was the case. Now I know that I don't need to go hunting for a possibly non-existent bug that somehow messed up the settings somewhere along the way to the function that was raising the exception.

Thanks for the bug reports and patience while I try to resolve the issues!

**Comment by jimkaiseriv** [comment]
No problem. Thanks again for your work!
