### ISSUE TITLE
[ST3] Configure SublimePapyrus.ini and build system for -all parameter

### ISSUE THREAD

**Issue by Scrivener07** [Kapiainen/SublimePapyrus#7]
I am trying to configure the papyrus build system to compile every single script in a specified folder where that folder is the directory of the **currently selected tab** in ST3, to avoid rebuilding unwanted directories such as ..\Skyrim\Data\Scripts\Source\*.psc. Ive read this is done by passing a directory instead of a file as the first argument and setting the -all flag.

Here is how Ive configured the ini file.
```
[Skyrim]
scripts=D:\Games\Steam\steamapps\common\skyrim\Data\Scripts\Source
compiler=D:\Games\Steam\steamapps\common\skyrim\Papyrus Compiler\PapyrusCompiler.exe
output=D:\Games\Steam\steamapps\common\skyrim\Data\Scripts
flags=TESV_Papyrus_Flags.flg
[Import]
path0=M:\TES5\Wrye\Bash Installers\Scribe Gameplay\Scripts\Source
path1=M:\TES5\Wrye\Bash Installers\Scribe Toxicity\Scripts\Source
path2=M:\TES5\Wrye\Bash Installers\Scribe Vitality\Scripts\Source
[Debug]
arg0=all
```

When I execute the build system I get this output..
```
Folder "D:\Games\Steam\steamapps\common\skyrim\Papyrus Compiler\ScribeVitality_ConfigBase.psc" does not exist
[Finished in 0.1s]
```

And further Ive also tried adding a new build system with the absolute directory.
```
{
	"target": "compile_papyrus",
	"cmd": "M:\\TES5\\Wrye\\Bash Installers\\Scribe Vitality\\Scripts\\Source",
	"file_regex": "^(.*\\.psc)\\(([0-9]*),([0-9]*)\\):\\s*(.*)$",
	"selector": "source.papyrus"
}
```
Which gives the following output..
```
Folder "D:\Games\Steam\steamapps\common\skyrim\Papyrus Compiler\Source" does not exist
[Finished in 0.1s]
```

This -all parameter seems to be changing the working directory to PapyrusCompiler.exe its self. I would appreciate any help configuring this as its been a very long time since Ive done any TES5 modding.

**Comment by Kapiainen** [comment]
Looks like I'll need to modify the command that runs the compiler so that it properly supports the **-all** flag. I can also add a new command that always runs the compiler with the **-all** flag so that one can quickly switch between the two ways of compiling (single file and batch) without having to go back and modify the INI file. These modifications should not require much time to implement and test, but it won't happen until I get home from work (about 8 hours after this is posted).

**Comment by Kapiainen** [comment]
The [new release](https://github.com/Kapiainen/SublimePapyrus/releases/tag/2015.08.03) adds better support for batch compiling and should solve the issue you encountered. Running the new *Batch compile* command on an open file will compile all .psc files in the folder that contains the open file. Alternatively you can use the *Papyrus - batch* build system to do the same thing (CTRL+SHIFT+B is the default shortcut in ST3 to quickly switch between build systems) or create a new shortcut that runs the *batch_compile_papyrus* command.

**Comment by Scrivener07** [comment]
Nice release, everything is working as expected. Thanks for the fast response!
