### ISSUE TITLE
Prevent scripts folder from batch compiling

### ISSUE THREAD

**Issue by Scrivener07** [Kapiainen/SublimePapyrus#8]
A setting to prevent the folder containing the vanilla Skyrim .psc files from being batch compiled would be an enhancement. Maybe as an ini setting? If I remember correctly I read on the CK wiki you should never batch compile the scripts folder from the CK script editor so maybe it should be prevented on the command line anyway.

**Comment by Kapiainen** [comment]
I assume that this is only a problem when the script sources of one's mod are not separated from other script sources?

I can probably add a confirmation prompt to stop accidental batch compilation of the folder defined by the *scripts* option in *SublimePapyrus.ini* and add a setting to disable the prompt for those who need to frequently batch compile files in the folder defined by the *scripts* option.

**Comment by Scrivener07** [comment]
Some times when Im looking at base scripts next to my project scripts I get a little trigger happy with the batch build and accidentally start building the vanilla script folder. Ive gotta scramble for the cancel build shortcut and restore the scripts with my mod manager.

Its really my fault but I cant think of a reason anyone would ever want to rebuild the whole script folder unless their scripts are the only ones there (unlikely).

**Comment by Kapiainen** [comment]
I have implemented a prompt that warns about the potential dangers of batch compiling the folder defined by the *scripts* option in the INI file. There is also a setting for completely disabling the prompt in case someone has their INI file set up in such a way that this prompt would not be applicable and only an annoyance.

I will push the update to the repository once I have slept and had a chance to test the implementation a bit more.

**Comment by Kapiainen** [comment]
Took longer than I had initially anticipated due to a lack of time, but the new release, which includes the batch compilation warning, is now available.
